//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Sultanlar.ClassLib.Kaan {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(classResult))]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SultanlarRaporOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::Sultanlar.ClassLib.Properties.Settings.Default.Sultanlar_ClassLib_Kaan_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SultanlarRaporCompletedEventHandler SultanlarRaporCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SultanlarRapor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public resultB2BSatisRapor SultanlarRapor(Authentication auth, System.DateTime ilktarih, System.DateTime sontarih) {
            object[] results = this.Invoke("SultanlarRapor", new object[] {
                        auth,
                        ilktarih,
                        sontarih});
            return ((resultB2BSatisRapor)(results[0]));
        }
        
        /// <remarks/>
        public void SultanlarRaporAsync(Authentication auth, System.DateTime ilktarih, System.DateTime sontarih) {
            this.SultanlarRaporAsync(auth, ilktarih, sontarih, null);
        }
        
        /// <remarks/>
        public void SultanlarRaporAsync(Authentication auth, System.DateTime ilktarih, System.DateTime sontarih, object userState) {
            if ((this.SultanlarRaporOperationCompleted == null)) {
                this.SultanlarRaporOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSultanlarRaporOperationCompleted);
            }
            this.InvokeAsync("SultanlarRapor", new object[] {
                        auth,
                        ilktarih,
                        sontarih}, this.SultanlarRaporOperationCompleted, userState);
        }
        
        private void OnSultanlarRaporOperationCompleted(object arg) {
            if ((this.SultanlarRaporCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SultanlarRaporCompleted(this, new SultanlarRaporCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Authentication {
        
        private string usernameField;
        
        private string passwordField;
        
        private string idField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SatisRaporSatir {
        
        private short fATURATURUField;
        
        private short iPTALField;
        
        private string mUSTERIKODUField;
        
        private string mUSTERIADIField;
        
        private string mUSTERIILField;
        
        private string fATURANOField;
        
        private string fATURATARIHIField;
        
        private string uRUNKODUField;
        
        private string uRUNADIField;
        
        private long sATISADEDIField;
        
        private decimal sATISNETFIYATField;
        
        /// <remarks/>
        public short FATURATURU {
            get {
                return this.fATURATURUField;
            }
            set {
                this.fATURATURUField = value;
            }
        }
        
        /// <remarks/>
        public short IPTAL {
            get {
                return this.iPTALField;
            }
            set {
                this.iPTALField = value;
            }
        }
        
        /// <remarks/>
        public string MUSTERIKODU {
            get {
                return this.mUSTERIKODUField;
            }
            set {
                this.mUSTERIKODUField = value;
            }
        }
        
        /// <remarks/>
        public string MUSTERIADI {
            get {
                return this.mUSTERIADIField;
            }
            set {
                this.mUSTERIADIField = value;
            }
        }
        
        /// <remarks/>
        public string MUSTERIIL {
            get {
                return this.mUSTERIILField;
            }
            set {
                this.mUSTERIILField = value;
            }
        }
        
        /// <remarks/>
        public string FATURANO {
            get {
                return this.fATURANOField;
            }
            set {
                this.fATURANOField = value;
            }
        }
        
        /// <remarks/>
        public string FATURATARIHI {
            get {
                return this.fATURATARIHIField;
            }
            set {
                this.fATURATARIHIField = value;
            }
        }
        
        /// <remarks/>
        public string URUNKODU {
            get {
                return this.uRUNKODUField;
            }
            set {
                this.uRUNKODUField = value;
            }
        }
        
        /// <remarks/>
        public string URUNADI {
            get {
                return this.uRUNADIField;
            }
            set {
                this.uRUNADIField = value;
            }
        }
        
        /// <remarks/>
        public long SATISADEDI {
            get {
                return this.sATISADEDIField;
            }
            set {
                this.sATISADEDIField = value;
            }
        }
        
        /// <remarks/>
        public decimal SATISNETFIYAT {
            get {
                return this.sATISNETFIYATField;
            }
            set {
                this.sATISNETFIYATField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resultB2BSatisRapor))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class classResult {
        
        private bool hataField;
        
        private string hataMesajiField;
        
        /// <remarks/>
        public bool Hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
            }
        }
        
        /// <remarks/>
        public string HataMesaji {
            get {
                return this.hataMesajiField;
            }
            set {
                this.hataMesajiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class resultB2BSatisRapor : classResult {
        
        private SatisRaporSatir[] itemsField;
        
        /// <remarks/>
        public SatisRaporSatir[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SultanlarRaporCompletedEventHandler(object sender, SultanlarRaporCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SultanlarRaporCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SultanlarRaporCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultB2BSatisRapor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultB2BSatisRapor)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591