//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sultanlar.WinServis.KaanGida {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authentication", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Authentication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="classResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sultanlar.WinServis.KaanGida.resultB2BSatisRapor))]
    public partial class classResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool HataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HataMesajiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Hata {
            get {
                return this.HataField;
            }
            set {
                if ((this.HataField.Equals(value) != true)) {
                    this.HataField = value;
                    this.RaisePropertyChanged("Hata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HataMesaji {
            get {
                return this.HataMesajiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataMesajiField, value) != true)) {
                    this.HataMesajiField = value;
                    this.RaisePropertyChanged("HataMesaji");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="resultB2BSatisRapor", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class resultB2BSatisRapor : Sultanlar.WinServis.KaanGida.classResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sultanlar.WinServis.KaanGida.SatisRaporSatir[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Sultanlar.WinServis.KaanGida.SatisRaporSatir[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SatisRaporSatir", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SatisRaporSatir : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short FATURATURUField;
        
        private short IPTALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MUSTERIKODUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MUSTERIADIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MUSTERIILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FATURANOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FATURATARIHIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URUNKODUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URUNADIField;
        
        private long SATISADEDIField;
        
        private decimal SATISNETFIYATField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short FATURATURU {
            get {
                return this.FATURATURUField;
            }
            set {
                if ((this.FATURATURUField.Equals(value) != true)) {
                    this.FATURATURUField = value;
                    this.RaisePropertyChanged("FATURATURU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short IPTAL {
            get {
                return this.IPTALField;
            }
            set {
                if ((this.IPTALField.Equals(value) != true)) {
                    this.IPTALField = value;
                    this.RaisePropertyChanged("IPTAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MUSTERIKODU {
            get {
                return this.MUSTERIKODUField;
            }
            set {
                if ((object.ReferenceEquals(this.MUSTERIKODUField, value) != true)) {
                    this.MUSTERIKODUField = value;
                    this.RaisePropertyChanged("MUSTERIKODU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MUSTERIADI {
            get {
                return this.MUSTERIADIField;
            }
            set {
                if ((object.ReferenceEquals(this.MUSTERIADIField, value) != true)) {
                    this.MUSTERIADIField = value;
                    this.RaisePropertyChanged("MUSTERIADI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string MUSTERIIL {
            get {
                return this.MUSTERIILField;
            }
            set {
                if ((object.ReferenceEquals(this.MUSTERIILField, value) != true)) {
                    this.MUSTERIILField = value;
                    this.RaisePropertyChanged("MUSTERIIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FATURANO {
            get {
                return this.FATURANOField;
            }
            set {
                if ((object.ReferenceEquals(this.FATURANOField, value) != true)) {
                    this.FATURANOField = value;
                    this.RaisePropertyChanged("FATURANO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string FATURATARIHI {
            get {
                return this.FATURATARIHIField;
            }
            set {
                if ((object.ReferenceEquals(this.FATURATARIHIField, value) != true)) {
                    this.FATURATARIHIField = value;
                    this.RaisePropertyChanged("FATURATARIHI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string URUNKODU {
            get {
                return this.URUNKODUField;
            }
            set {
                if ((object.ReferenceEquals(this.URUNKODUField, value) != true)) {
                    this.URUNKODUField = value;
                    this.RaisePropertyChanged("URUNKODU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string URUNADI {
            get {
                return this.URUNADIField;
            }
            set {
                if ((object.ReferenceEquals(this.URUNADIField, value) != true)) {
                    this.URUNADIField = value;
                    this.RaisePropertyChanged("URUNADI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public long SATISADEDI {
            get {
                return this.SATISADEDIField;
            }
            set {
                if ((this.SATISADEDIField.Equals(value) != true)) {
                    this.SATISADEDIField = value;
                    this.RaisePropertyChanged("SATISADEDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public decimal SATISNETFIYAT {
            get {
                return this.SATISNETFIYATField;
            }
            set {
                if ((this.SATISNETFIYATField.Equals(value) != true)) {
                    this.SATISNETFIYATField = value;
                    this.RaisePropertyChanged("SATISNETFIYAT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KaanGida.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name auth from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SultanlarRapor", ReplyAction="*")]
        Sultanlar.WinServis.KaanGida.SultanlarRaporResponse SultanlarRapor(Sultanlar.WinServis.KaanGida.SultanlarRaporRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SultanlarRaporRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SultanlarRapor", Namespace="http://tempuri.org/", Order=0)]
        public Sultanlar.WinServis.KaanGida.SultanlarRaporRequestBody Body;
        
        public SultanlarRaporRequest() {
        }
        
        public SultanlarRaporRequest(Sultanlar.WinServis.KaanGida.SultanlarRaporRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SultanlarRaporRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Sultanlar.WinServis.KaanGida.Authentication auth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime ilktarih;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime sontarih;
        
        public SultanlarRaporRequestBody() {
        }
        
        public SultanlarRaporRequestBody(Sultanlar.WinServis.KaanGida.Authentication auth, System.DateTime ilktarih, System.DateTime sontarih) {
            this.auth = auth;
            this.ilktarih = ilktarih;
            this.sontarih = sontarih;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SultanlarRaporResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SultanlarRaporResponse", Namespace="http://tempuri.org/", Order=0)]
        public Sultanlar.WinServis.KaanGida.SultanlarRaporResponseBody Body;
        
        public SultanlarRaporResponse() {
        }
        
        public SultanlarRaporResponse(Sultanlar.WinServis.KaanGida.SultanlarRaporResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SultanlarRaporResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Sultanlar.WinServis.KaanGida.resultB2BSatisRapor SultanlarRaporResult;
        
        public SultanlarRaporResponseBody() {
        }
        
        public SultanlarRaporResponseBody(Sultanlar.WinServis.KaanGida.resultB2BSatisRapor SultanlarRaporResult) {
            this.SultanlarRaporResult = SultanlarRaporResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Sultanlar.WinServis.KaanGida.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Sultanlar.WinServis.KaanGida.Service1Soap>, Sultanlar.WinServis.KaanGida.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sultanlar.WinServis.KaanGida.SultanlarRaporResponse Sultanlar.WinServis.KaanGida.Service1Soap.SultanlarRapor(Sultanlar.WinServis.KaanGida.SultanlarRaporRequest request) {
            return base.Channel.SultanlarRapor(request);
        }
        
        public Sultanlar.WinServis.KaanGida.resultB2BSatisRapor SultanlarRapor(Sultanlar.WinServis.KaanGida.Authentication auth, System.DateTime ilktarih, System.DateTime sontarih) {
            Sultanlar.WinServis.KaanGida.SultanlarRaporRequest inValue = new Sultanlar.WinServis.KaanGida.SultanlarRaporRequest();
            inValue.Body = new Sultanlar.WinServis.KaanGida.SultanlarRaporRequestBody();
            inValue.Body.auth = auth;
            inValue.Body.ilktarih = ilktarih;
            inValue.Body.sontarih = sontarih;
            Sultanlar.WinServis.KaanGida.SultanlarRaporResponse retVal = ((Sultanlar.WinServis.KaanGida.Service1Soap)(this)).SultanlarRapor(inValue);
            return retVal.Body.SultanlarRaporResult;
        }
    }
}
